# -*- coding: utf-8 -*-
"""Neural_network(Diabetes)).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10l1p3QfXBpmoMKGnCs_FMgpyBt-Tuhwp
"""

# CELL 1: IMPORTS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# CELL 2: DATA LOADING & EXPLORATORY SUMMARY
print("--- Loading Diabetes Dataset (Regression) ---")
data = load_diabetes()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target  # Continuous numerical values

print(f"Dataset Shape: {X.shape[0]} rows, {X.shape[1]} features")
print(f"Target Feature (Disease Progression) Range: {y.min()} to {y.max()}")
print("\nFirst 5 rows of features:")
display(X.head())

# CELL 3: PREPROCESSING
# Split the data (80% train, 20% test).
# Note: stratify=y is REMOVED because y is continuous, not categorical.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the scaler
scaler = StandardScaler()

# Fit on training data AND transform it.
# Transform test data to prevent data leakage.
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data successfully split and scaled!")

# CELL 4: MODEL BUILDING
# Initialize a sequential model
model = Sequential([
    # Input layer and 1st Hidden Layer
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.2),

    # 2nd Hidden Layer
    Dense(32, activation='relu'),
    Dropout(0.2),

    # Output Layer
    # CHANGED: 1 neuron with 'linear' activation for continuous output
    Dense(1, activation='linear')
])

# Compile the model
# CHANGED: Loss is Mean Squared Error (mse), Metric is Mean Absolute Error (mae)
model.compile(optimizer='adam',
              loss='mse',
              metrics=['mae'])

print("--- Model Architecture ---")
model.summary()

# CELL 5: TRAINING WITH EARLY STOPPING
# Define EarlyStopping callback
early_stop = EarlyStopping(
    monitor='val_loss',     # We are monitoring the validation MSE
    patience=20,            # Wait 20 epochs for improvement
    restore_best_weights=True
)

print("--- Starting Training ---")
history = model.fit(
    X_train_scaled, y_train,
    epochs=200,
    validation_split=0.2,
    callbacks=[early_stop],
    batch_size=32,
    verbose=1
)

# CELL 6: EVALUATION & VISUALIZATION
print("--- Evaluating on Test Set ---")
# Evaluate returns loss (MSE) and our chosen metric (MAE)
test_mse, test_mae = model.evaluate(X_test_scaled, y_test, verbose=0)

# Generate predictions
y_pred = model.predict(X_test_scaled).flatten() # Flatten converts 2D output to 1D array

# Calculate R-squared
r2 = r2_score(y_test, y_pred)

print(f"Test Mean Squared Error (MSE): {test_mse:.2f}")
print(f"Test Mean Absolute Error (MAE): {test_mae:.2f}")
print(f"Test R-squared Score: {r2:.4f}\n")

# Plotting Training History
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot Loss (MSE)
axes[0].plot(history.history['loss'], label='Training Loss (MSE)')
axes[0].plot(history.history['val_loss'], label='Validation Loss (MSE)')
axes[0].set_title('Model Loss Over Epochs')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('MSE')
axes[0].legend()

# Plot True vs Predicted Scatter Plot
axes[1].scatter(y_test, y_pred, alpha=0.7, color='b')
# Draw a perfect prediction reference line (y = x)
min_val = min(np.min(y_test), np.min(y_pred))
max_val = max(np.max(y_test), np.max(y_pred))
axes[1].plot([min_val, max_val], [min_val, max_val], color='red', linestyle='--', linewidth=2, label='Perfect Prediction')

axes[1].set_title('True Values vs Predictions')
axes[1].set_xlabel('True Disease Progression')
axes[1].set_ylabel('Predicted Progression')
axes[1].legend()

plt.tight_layout()
plt.show()

